name: CML Model Report

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  cml-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CML
        run: npm install -g @dvcorg/cml

      - name: Post CML report to PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cml comment create reports/cml_report.md
